apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: blue
  labels:
    app: react-app
    env: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
      env: blue
  template:
    metadata:
      labels:
        app: react-app
        env: blue
    spec:
      containers:
      - name: react-app
        image: surendradev101/react-app:0a935c054aaca20933a7f5e4474566e09dc18190
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
